# Generated by Django 2.2.5 on 2021-04-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(help_text='Longitude')),
                ('Y', models.FloatField(help_text='Latitude')),
                ('Unique_Squirrel_ID', models.CharField(max_length=100, null=True, unique=True)),
                ('Hectare', models.CharField(max_length=100)),
                ('Shift', models.CharField(blank=True, max_length=2)),
                ('Date', models.DateField(blank=True)),
                ('Hectare_Squirrel_Number', models.CharField(max_length=100)),
                ('Age', models.CharField(blank=True, max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, max_length=100)),
                ('Location', models.CharField(blank=True, max_length=100)),
                ('Specific_Location', models.CharField(blank=True, max_length=100)),
                ('Running', models.BooleanField(blank=True)),
                ('Chasing', models.BooleanField(blank=True)),
                ('Climbing', models.BooleanField(blank=True)),
                ('Eating', models.BooleanField(blank=True)),
                ('Foraging', models.BooleanField(blank=True)),
                ('Other_activities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField(blank=True)),
                ('Quaas', models.BooleanField(blank=True)),
                ('Moans', models.BooleanField(blank=True)),
                ('Tail_flags', models.BooleanField(blank=True)),
                ('Tail_twitches', models.BooleanField(blank=True)),
                ('Approaches', models.BooleanField(blank=True)),
                ('Indifferent', models.BooleanField(blank=True)),
                ('Runs_from', models.BooleanField(blank=True)),
            ],
        ),
    ]
