# Generated by Django 2.2.5 on 2021-04-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel', '0002_auto_20210408_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='Specific_Location',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(blank=True, choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('Cinnamon', 'Cinnamon'), ('Gray', 'Gray')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(blank=True, choices=[('AM', 'AM'), ('PM', 'PM')], max_length=100),
        ),
    ]
