# Generated by Django 2.2.5 on 2021-04-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squirrel', '0003_auto_20210408_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Specific_Location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
